FROM golang:1.13.4-alpine3.10

ADD . /go/src/accountapi-client

WORKDIR /go/src/accountapi-client

RUN apk update && apk add git

RUN go get accountapi-client
RUN go get github.com/smartystreets/goconvey/convey
RUN go install